version: "3.8"

services:
  mongodb:
    image: bitnami/mongodb:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - mongodb_data:/bitnami/mongodb
    networks:
      - backend-network

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3333:3333
    restart: unless-stopped
    depends_on:
      - mongodb
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/auth_info_baileys:/app/auth_info_baileys
      - uploads:/app/uploads
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    networks:
      - backend-network
      - frontend-network

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - frontend-network

volumes:
  mongodb_data:
  backend_node_modules:
  uploads:

networks:
  backend-network:
  frontend-network:
